var x = 6;
var y = 10;
var name1 = 'John';
var age = 25;
var isStudent = true;
var fruits = ['apple', 'banana', 'orange'];
var emptyArray = [];
var person = { name: 'Alice', age: 30 };
console.log("Is x == 6? I predict True.");
console.log(x == 6);
console.log("Is name1 === 'John'? I predict True.");
console.log(name1 === 'John');
console.log("Is age >= 21? I predict True.");
console.log(age >= 21);
console.log("Is isStudent === true? I predict True.");
console.log(isStudent === true);
console.log("Is fruits.length > 0? I predict True.");
console.log(fruits.length > 0);
console.log("Is x != y? I predict False.");
console.log(x != y);
console.log("Is emptyArray.length === 0? I predict False.");
console.log(emptyArray.length === 0);
console.log("Is person.name === 'Alice' and person.age === 30? I predict False.");
console.log(person.name === 'Alice' && person.age === 30);
console.log("Is x === 5? I predict False.");
console.log(x === 5);
console.log("Is name !== 'john'? I predict True.");
console.log(name1 !== 'john');
